// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// test_matrix_exponential_multiply
Rcpp::List test_matrix_exponential_multiply(arma::mat A, arma::mat B, double t, arma::mat g);
RcppExport SEXP _coaldecoder_test_matrix_exponential_multiply(SEXP ASEXP, SEXP BSEXP, SEXP tSEXP, SEXP gSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type A(ASEXP);
    Rcpp::traits::input_parameter< arma::mat >::type B(BSEXP);
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type g(gSEXP);
    rcpp_result_gen = Rcpp::wrap(test_matrix_exponential_multiply(A, B, t, g));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP _rcpp_module_boot_particle();

static const R_CallMethodDef CallEntries[] = {
    {"_coaldecoder_test_matrix_exponential_multiply", (DL_FUNC) &_coaldecoder_test_matrix_exponential_multiply, 4},
    {"_rcpp_module_boot_particle", (DL_FUNC) &_rcpp_module_boot_particle, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_coaldecoder(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
